mod enigma;
mod lib;
use crate::enigma::enigma_machine::EnigmaMachine;

// TODO: Find some test material with plugboards, double-stepping and ring settings
// TODO: Make sure all comments are complete and accurate

fn main() {
    let mut my_enigma = EnigmaMachine::new(
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ".to_owned(),           // plugboard cipher
        "BDFHJLCPRTXVZNYEIWGAKMUSQO".to_owned(), 10, 0,    // rightmost rotor cipher, offset and ring setting
        "AJDKSIRUXBLHWTMCQGZNPYFVOE".to_owned(), 2, 0,     // middle rotor cipher, offset and ring setting
        "EKMFLGDQVZNTOWYHXUSPAIBRCJ".to_owned(), 12, 0,    // leftmost rotor cipher, offset and ring setting
        "YRUHQSLDPXNGOKMIEBFZCWVJAT".to_owned()            // reflector cipher
    );
    my_enigma.set_triggers(vec![22], vec![5], vec![17]);   // set rotor tunrover points
    let transformed:String = my_enigma.transform_message("ENIGMA REVEALED".to_owned());
    println!("{}", transformed);
    my_enigma.set_rotor_positions(10, 2, 12);
    let retransformed:String = my_enigma.transform_message(transformed);
    println!("{}", retransformed);
    my_enigma.set_rotor_positions(10, 2, 12);
    let encoded:String = my_enigma.transform_message("THE SUN WAS SHINING ON THE SEA SHINING WITH ALL HIS MIGHT HE DID HIS VERY BEST TO MAKE THE BILLOWS SMOOTH AND BRIGHT AND THIS WAS ODD BECAUSE IT WAS THE MIDDLE OF THE NIGHT THE MOON WAS SHINING SULKILY BECAUSE SHE THOUGHT THE SUN HAD GOT NO BUSINESS TO BE THERE AFTER THE DAY WAS DONE ITS VERY RUDE OF HIM SHE SAID TO COME AND SPOIL THE FUN THE SEA WAS WET AS WET COULD BE THE SANDS WERE DRY AS DRY YOU COULD NOT SEE A CLOUD BECAUSE NO CLOUD WAS IN THE SKY NO BIRDS WERE FLYING OVERHEAD THERE WERE NO BIRDS TO FLY THE WALRUS AND THE CARPENTER WERE WALKING CLOSE AT HAND THEY WEPT LIKE ANYTHING TO SEE SUCH QUANTITIES OF SAND IF THIS WERE ONLY CLEARED AWAY THEY SAID IT WOULD BE GRAND IF SEVEN MAIDS WITH SEVEN MOPS SWEPT IT FOR HALF A YEAR DO YOU SUPPOSE THE WALRUS SAID THAT THEY COULD GET IT CLEAR I DOUBT IT SAID THE CARPENTER AND SHED A BITTER TEAR O OYSTERS COME AND WALK WITH US THE WALRUS DID BESEECH A PLEASANT WALK A PLEASANT TALK ALONG THE BRINY BEACH WE CANNOT DO WITH MORE THAN FOUR TO GIVE A HAND TO EACH THE ELDEST OYSTER LOOKED AT HIM BUT NEVER A WORD HE SAID THE ELDEST OYSTER WINKED HIS EYE AND SHOOK HIS HEAVY HEAD MEANING TO SAY HE DID NOT CHOOSE TO LEAVE THE OYSTER-BED BUT FOUR YOUNG OYSTERS HURRIED UP ALL EAGER FOR THE TREAT THEIR COATS WERE BRUSHED THEIR FACES WASHED THEIR SHOES WERE CLEAN AND NEAT AND THIS WAS ODD BECAUSE YOU KNOW THEY HADNT ANY FEET FOUR OTHER OYSTERS FOLLOWED THEM AND YET ANOTHER FOUR AND THICK AND FAST THEY CAME AT LAST AND MORE AND MORE AND MORE ALL HOPPING THROUGH THE FROTHY WAVES AND SCRAMBLING TO THE SHORE THE WALRUS AND THE CARPENTER WALKED ON A MILE OR SO AND THEN THEY RESTED ON A ROCK CONVENIENTLY LOW AND ALL THE LITTLE OYSTERS STOOD AND WAITED IN A ROW THE TIME HAS COME THE WALRUS SAID TO TALK OF MANY THINGS OF SHOES AND SHIPS AND SEALING-WAX OF CABBAGES AND KINGS AND WHY THE SEA IS BOILING HOT AND WHETHER PIGS HAVE WINGS BUT WAIT A BIT THE OYSTERS CRIED BEFORE WE HAVE OUR CHAT FOR SOME OF US ARE OUT OF BREATH AND ALL OF US ARE FAT NO HURRY SAID THE CARPENTER THEY THANKED HIM MUCH FOR THAT A LOAF OF BREAD THE WALRUS SAID IS WHAT WE CHIEFLY NEED PEPPER AND VINEGAR BESIDES ARE VERY GOOD INDEED NOW IF YOURE READY OYSTERS DEAR WE CAN BEGIN TO FEED BUT NOT ON US THE OYSTERS CRIED TURNING A LITTLE BLUE AFTER SUCH KINDNESS THAT WOULD BE A DISMAL THING TO DO THE NIGHT IS FINE THE WALRUS SAID DO YOU ADMIRE THE VIEW IT WAS SO KIND OF YOU TO COME AND YOU ARE VERY NICE THE CARPENTER SAID NOTHING BUT CUT US ANOTHER SLICE I WISH YOU WERE NOT QUITE SO DEAF IVE HAD TO ASK YOU TWICE IT SEEMS A SHAME THE WALRUS SAID TO PLAY THEM SUCH A TRICK AFTER WEVE BROUGHT THEM OUT SO FAR AND MADE THEM TROT SO QUICK THE CARPENTER SAID NOTHING BUT THE BUTTERS SPREAD TOO THICK I WEEP FOR YOU THE WALRUS SAID I DEEPLY SYMPATHIZE WITH SOBS AND TEARS HE SORTED OUT THOSE OF THE LARGEST SIZE HOLDING HIS POCKET-HANDKERCHIEF BEFORE HIS STREAMING EYES O OYSTERS SAID THE CARPENTER YOUVE HAD A PLEASANT RUN SHALL WE BE TROTTING HOME AGAIN BUT ANSWER CAME THERE NONE AND THIS WAS SCARCELY ODD BECAUSE THEYD EATEN EVERY ONE".to_owned());
    println!("{}", encoded);
    my_enigma.set_rotor_positions(10, 2, 12);
    let decoded:String = my_enigma.transform_message(encoded);
    println!("{}", decoded);
}
